version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - "5775:5775"   # Thrift compact
      - "5778:5778"   # HTTP admin interface
      - "14250:14250" # Thrift binary
      - "14267:14267" # Zipkin
      - "14268:14268" # HTTP
      - "14300:14300" # gRPC
      - "16686:16686" # UI
      - "6831:6831/udp"
      - "6832:6832/udp" 
      - "4317:4317"
      - "4318:4318"     
      - "14269:14269"
      - "9411:9411" 
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - jaeger-network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: jaeger
      POSTGRES_PASSWORD: jaeger_password
      POSTGRES_DB: jaeger
    ports:
      - "5432:5432"
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge
